# Generated by Django 2.2 on 2019-06-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='reported_date',
            field=models.DateField(),
        ),
    ]
