# Generated by Django 2.2 on 2019-06-15 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190615_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='reported_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
