# Generated by Django 2.2 on 2019-06-15 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190615_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='reported_date',
        ),
        migrations.AddField(
            model_name='crime',
            name='reported_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
