# Generated by Django 2.2 on 2019-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190615_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='crime',
            name='crime',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='crime',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crime',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
